text('Trabajar con texto',10,300,'blue',{font: "70px Arial"})
text('Tamaño del Texto',10,400,'red',{fontSize: "12px"})
text('Tildes : Canción',300,20,'gree',{fontSize: "12px"})
text('Texto italic ',0,0,'yellow',{fontSize: "30px",fontStyle:"italic"})
text('Texto largo colocar varias lineas',200,100,'orange',{fontSize: "50px",fontStyle:"italic",wordWrap:"true",wordWrapWidth:350})